<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Complaint $complaint
 */
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Complaint Letter</title>
</head>
<body style="margin: 0; padding: 0; font-family: Arial, sans-serif; font-size: 13px;">

<table width="100%" height="1122" style="border-collapse: collapse; table-layout: fixed;" cellpadding="0" cellspacing="0">
    <!-- Top Banner -->
    <tr style="height: 120px;">
        <td>
            <?= $this->Html->image('top.png', ['width' => '80%', 'style' => 'display:block;', 'fullBase' => true]) ?>
        </td>
    </tr>

    <!-- Main Content (Letter Body) -->
    <tr style="height: 882px;">
        <td style="padding: 40px; vertical-align: top;">
            <table width="100%" style="font-size: 13px;">
                <tr>
                    <td width="65%"></td>
                    <td><strong>Our Letter</strong></td>
                    <td>:</td>
                    <td>PUNDANA/50(<?= h($complaint->id) ?>)</td>
                </tr>
                <tr>
                    <td></td>
                    <td><strong>Tarikh</strong></td>
                    <td>:</td>
                    <td><?= date('d F Y', strtotime($complaint->created)) ?></td>
                </tr>
            </table>

            <br><br>

            <?= h($complaint->student->name ?? 'Student Name') ?><br>
            Kolej Jasmine,<br>
            Persiaran Pulau Angsa, Bandar Nusa Rhu<br>
            40170 Shah Alam,<br>
            Selangor Darul Ehsan,<br>
            Malaysia

            <br><br>
            <strong style="text-transform: uppercase;">Acknowledgement and Resolution of Your Complaint <?= h(date('Y')) ?></strong>
            <br><br>

            We acknowledge receipt of your complaint dated <strong><?= h($complaint->complaint_date) ?></strong>,
            regarding <strong><?= h($complaint->complaint_type) ?></strong>.

            <br><br>

            After reviewing your submission and conducting a preliminary investigation, we understand the nature and urgency of the issue. The following steps have been or will be taken to resolve the matter:

            <br><br>
            1. Complaint Reference ID: <strong><?= h($complaint->id) ?></strong><br>
            2. Investigation Status:
            <strong>
                <?php
                    if ($complaint->status == 2) echo 'Archived';
                    elseif ($complaint->status == 1) echo 'Active';
                    else echo 'Disabled';
                ?>
            </strong><br>
            3. Description: <strong><?= h($complaint->description) ?></strong><br>
            4. Expected Resolution Date: <strong><?= h($complaint->resolution_date ?? 'Pending') ?></strong>

            <br><br>
            We appreciate your patience and cooperation. Should you find the resolution unsatisfactory or if the issue persists, please contact the hostel office or reply to this letter.

            <br><br>
            Thank you for bringing this matter to our attention.

            <br><br>
            Warm regards,<br><br>

            <strong>Zainal Nur Danish bin Zainal</strong><br>
            Head of Warden<br>
            kolejJasmine@gmail.com<br>
            +60 301722456<br><br>

            <small><i>This letter is generated by computer. No signature is required.</i></small>
        </td>
    </tr>
<br></br>
<br></br>
<br></br>
    <!-- Bottom Banner -->
    <tr style="height: 120px;">
        <td>
            <?= $this->Html->image('bottom.png', ['width' => '100%', 'style' => 'display:block;', 'fullBase' => true]) ?>
        </td>
    </tr>
</table>

</body>
</html>
