<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Complaint $complaint
 * @var int $total_complaints_active
 * @var int $total_complaints_disabled
 * @var int $total_complaints_archived
 * @var int $electricityCount
 * @var int $plumbingCount
 * @var int $internetCount
 * @var int $waterCount
 * @var int $maintenanceCount
 * @var int $othersCount
 */
?>

<div class="line mb-4"></div>

<style>
.putih {
    background-color: #ffffff;
    color: #000000;
}
.capital {
    text-transform: uppercase;
}
</style>

<div class="row">
    <!-- LEFT: Complaint Letter -->
    <div class="col-md-9">
        <div class="card rounded-0 mb-3 border-0 shadow putih">
            <div class="card-body">
                <?= $this->Html->image('webroot/img/top.png', ['width' => '100%']) ?>

                <!-- Letter Metadata -->
                <div class="table-responsive mt-4 mb-3">
                    <table width="100%">
                        <tr>
                            <td width="70%"></td>
                            <td>Our Letter</td>
                            <td>:</td>
                            <td>PUNDANA/50(<?= h($complaint->id) ?>)</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>Tarikh</td>
                            <td>:</td>
                            <td><?= date('d F Y', strtotime($complaint->created)) ?></td>
                        </tr>
                    </table>
                </div>

                <?= h($complaint->student->name ?? 'Student Name') ?><br/>
                 Kolej Jasmine,<br>
            Persiaran Pulau Angsa, Bandar Nusa Rhu<br>
            40170 Shah Alam,<br>
            Selangor Darul Ehsan,<br>
            Malaysia


                <br><br>
                <b class="capital">Acknowledgement and Resolution of Your Complaint <?= h(date('Y')) ?></b>
                <br><br>

                We acknowledge receipt of your complaint dated <b><?= h($complaint->complaint_date) ?></b>,
                regarding <b><?= h($complaint->complaint_type) ?></b>.

                <br><br>
                After reviewing your submission and conducting a preliminary investigation, we understand the nature and urgency of the issue. The following steps have been or will be taken to resolve the matter:

                <br><br>
                1. Complaint Reference ID: <b><?= h($complaint->id) ?></b><br>
                2. Investigation Status: 
                <b>
                    <?php
                        if ($complaint->status == 1) echo 'Resolved';
                        else echo 'Pending';
                    ?>
                </b><br>
                3. Description: <b><?= h($complaint->description) ?></b><br>
                4. Expected Resolution Date: <b><?= h($complaint->resolution_date ?? 'Pending') ?></b>

                <br><br>
                We appreciate your patience and cooperation. Should you find the resolution unsatisfactory or if the issue persists, please contact the hostel office or reply to this letter.

                <br><br>
                Thank you for bringing this matter to our attention.

                <br><br>
                Warm regards,<br><br>

                <strong>Zainal Nur Danish bin Zainal</strong><br>
            Head of Warden<br>
            kolejJasmine@gmail.com<br>
            +60 301722456<br><br>

                <small><i>THIS LETTER IS GENERATED BY COMPUTER. NO SIGNATURE IS REQUIRED.</i></small>

            </div>
        </div>
    </div>

   <!-- RIGHT: Sidebar Dropdowns -->
<div class="col-md-3">
    <div class="card border-0 shadow mb-4">
        <div class="card-body">
            <h5 class="card-title">Actions</h5>

            <!-- Manage Dropdown -->
            <div class="dropdown mb-3">
                <button class="btn btn-outline-secondary w-100 dropdown-toggle" type="button" data-bs-toggle="dropdown">
                    <i class="fa-solid fa-bars"></i> Manage
                </button>
                <ul class="dropdown-menu w-100">
                    <li><?= $this->Html->link('✏️ Edit Complaint', ['action' => 'edit', $complaint->id], ['class' => 'dropdown-item']) ?></li>
                    <li><?= $this->Form->postLink('🗑 Delete Complaint', ['action' => 'delete', $complaint->id], ['confirm' => __('Are you sure you want to delete # {0}?', $complaint->id), 'class' => 'dropdown-item text-danger']) ?></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><?= $this->Html->link('📋 List Complaints', ['action' => 'index'], ['class' => 'dropdown-item']) ?></li>
                    <li><?= $this->Html->link('➕ New Complaint', ['action' => 'add'], ['class' => 'dropdown-item']) ?></li>
                </ul>
            </div>

            

            <!-- PDF Download Button -->
            <?= $this->Html->link(
                '<i class="fa-solid fa-file-pdf"></i> Download PDF',
                ['action' => 'pdf', $complaint->id],
                ['class' => 'btn btn-primary w-100', 'escape' => false]
            ) ?>
        </div>
    </div>
</div>

<!-- Chart.js CDN -->
<?= $this->Html->script('https://cdn.jsdelivr.net/npm/chart.js') ?>

<!-- Chart.js Scripts -->
<script>
document.addEventListener("DOMContentLoaded", function() {
    new Chart(document.getElementById('statusChart'), {
        type: 'bar',
        data: {
            labels: ['Active', 'Disabled', 'Archived'],
            datasets: [{
                label: 'Count',
                data: [<?= $total_complaints_active ?>, <?= $total_complaints_disabled ?>, <?= $total_complaints_archived ?>],
                backgroundColor: ['rgba(75, 192, 192, 0.5)', 'rgba(255, 99, 132, 0.5)', 'rgba(201, 203, 207, 0.5)'],
                borderColor: ['rgba(75, 192, 192, 1)', 'rgba(255, 99, 132, 1)', 'rgba(201, 203, 207, 1)'],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            plugins: { legend: { display: false } },
            scales: { y: { beginAtZero: true } }
        }
    });

    new Chart(document.getElementById('typeChart'), {
        type: 'pie',
        data: {
            labels: ['Electricity', 'Plumbing', 'Internet', 'Water', 'Maintenance', 'Others'],
            datasets: [{
                label: 'Type',
                data: [<?= $electricityCount ?>, <?= $plumbingCount ?>, <?= $internetCount ?>, <?= $waterCount ?>, <?= $maintenanceCount ?>, <?= $othersCount ?>],
                backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0', '#9966FF', '#FF9F40']
            }]
        },
        options: {
            responsive: true,
            plugins: { legend: { position: 'bottom' } }
        }
    });
});
</script>